/**
 * Prompt templates for Cursor agent testcase analysis.
 *
 * Instead of custom prompts, the agent reads and follows the actual skill files
 * from the nutest-py3-tests repo on Sourcegraph:
 *   - triage-cdp-test-failure skill for failed testcase triage
 *   - triage-rdm-deployment-failure skill for skipped testcase triage
 *
 * The skill files contain the complete triage methodology, log access tiers,
 * JIRA integration, Sourcegraph deep-dives, and report generation.
 */

const NUTEST_REPO = "nugerrit.ntnxdpro.com/nutest-py3-tests";
const SKILL_BASE = ".cursor/skills";

const CDP_SKILL_DIR = `${SKILL_BASE}/triage-cdp-test-failure`;

// All files in the triage-cdp-test-failure skill directory.
// The agent must read these via Sourcegraph during triage.
const CDP_SKILL_FILES = [
  `${CDP_SKILL_DIR}/SKILL.md`,
  `${CDP_SKILL_DIR}/archived-logs-reference.md`,
  `${CDP_SKILL_DIR}/ingest-reference.md`,
  `${CDP_SKILL_DIR}/extract-reference.md`,
  `${CDP_SKILL_DIR}/investigate-reference.md`,
  `${CDP_SKILL_DIR}/failure-patterns-reference.md`,
  `${CDP_SKILL_DIR}/jira-reference.md`,
  `${CDP_SKILL_DIR}/jita-task-mode-reference.md`,
  `${CDP_SKILL_DIR}/report-template-reference.md`,
  `${CDP_SKILL_DIR}/sourcegraph-reference.md`,
  `${CDP_SKILL_DIR}/live-cluster-reference.md`,
  `${CDP_SKILL_DIR}/telemetry-reference.md`,
  `${CDP_SKILL_DIR}/setup-guide.md`,
  `${CDP_SKILL_DIR}/jira_helper.py`,
];

const RDM_SKILL_DIR = `${SKILL_BASE}/triage-rdm-deployment-failure`;

/**
 * Build the prompt for analyzing a FAILED testcase.
 *
 * The agent reads the triage-cdp-test-failure SKILL.md from Sourcegraph and
 * executes its full workflow with the JITA log directory URL as input.
 */
export function buildFailedAnalysisPrompt(opts) {
  const {
    testcaseName = "",
    exceptionSummary = "",
    exception = "",
    stepsLog = "",
    nutestTestLog = "",
    testLogUrl = "",
    jiraTickets = [],
    failureStage = "",
  } = opts;

  const jiraLine = jiraTickets.length
    ? `- **Linked Jira:** ${jiraTickets.join(", ")}\n`
    : "";

  const fileList = CDP_SKILL_FILES
    .map((f, i) => `${i + 1}. \`${f}\``)
    .join("\n");

  return `## Your Task

You are triaging a failed nutest testcase. You MUST read and follow the
**triage-cdp-test-failure** skill from the nutest-py3-tests repository.

### Step 1 — Read ALL skill files

Use the **gw-sourcegraph** MCP server (\`sourcegraph__read_file\`) to read
every file in the skill directory. The repo is \`${NUTEST_REPO}\`.

**Start with SKILL.md** (it is the entry point and references all other files),
then read the remaining reference files as directed by the workflow:

${fileList}

Also list and read any files inside the \`${CDP_SKILL_DIR}/flows/\` subdirectory —
these contain service-specific investigation flows referenced by
\`failure-patterns-reference.md\`. Read the specific flow file that matches the
failing service/subsystem.

Read these files **before** you begin triage so you have the full methodology,
reference tables, report templates, and investigation patterns loaded.

### Step 2 — Execute the skill with this input

The triage mode is **Archived Logs Mode**. The log directory URL is:

\`\`\`
${testLogUrl || "NO LOG URL PROVIDED"}
\`\`\`

**Testcase context (for reference — the skill workflow will guide you):**
- **Testcase:** ${testcaseName}
- **Failure Stage:** ${failureStage || "Unknown"}
${jiraLine}- **Exception Summary:** ${exceptionSummary || "N/A"}

Exception / Traceback:
\`\`\`
${(exception || "N/A").slice(0, 5000)}
\`\`\`

${stepsLog ? `steps.log snippet:\n\`\`\`\n${stepsLog.slice(0, 3000)}\n\`\`\`\n` : ""}
${nutestTestLog ? `nutest_test.log snippet:\n\`\`\`\n${nutestTestLog.slice(0, 3000)}\n\`\`\`\n` : ""}

### Step 3 — Return structured results

After completing the skill's triage workflow, return your findings as JSON:

\`\`\`json
{
  "root_cause": "Evidence-backed root cause explanation (observed/inferred/unknown per skill discipline)",
  "classification": "Test Issue | Product Issue | Infra Issue | Flaky / Timing",
  "failing_code": {
    "file": "path/to/file",
    "line_range": "start-end",
    "snippet": "relevant code"
  },
  "suggested_fix": "Actionable fix or next step",
  "confidence": "High | Medium | Low",
  "related_components": ["service1", "service2"],
  "jira_duplicates": ["ENG-XXXXX"],
  "triage_report": "The full JIRA wiki markup report as generated by the skill"
}
\`\`\`

Respond ONLY with the JSON block.`;
}

/**
 * Build the prompt for analyzing a SKIPPED testcase.
 *
 * The agent reads the triage-rdm-deployment-failure SKILL.md from Sourcegraph
 * and executes its workflow.
 */
export function buildSkippedAnalysisPrompt(opts) {
  const {
    testcaseName = "",
    exceptionSummary = "",
    exception = "",
    stepsLog = "",
    nutestTestLog = "",
    testLogUrl = "",
    jiraTickets = [],
    failureStage = "",
  } = opts;

  const jiraLine = jiraTickets.length
    ? `- **Linked Jira:** ${jiraTickets.join(", ")}\n`
    : "";

  return `## Your Task

You are triaging a skipped nutest testcase (likely due to a deployment failure).
You MUST read and follow the **triage-rdm-deployment-failure** skill from the
nutest-py3-tests repository.

### Step 1 — Read ALL skill files

Use the **gw-sourcegraph** MCP server (\`sourcegraph__read_file\`) to read
the skill files. The repo is \`${NUTEST_REPO}\`.

1. **Start with:** \`${RDM_SKILL_DIR}/SKILL.md\`
2. Then read every reference file it points to inside \`${RDM_SKILL_DIR}/\`.
   Use \`sourcegraph__list_files\` on path \`${RDM_SKILL_DIR}\` to discover all
   files, then read each one.
3. Also read any \`flows/\` subdirectory files that match the deployment failure type.

Read these files **before** you begin triage so you have the full methodology loaded.

### Step 2 — Execute the skill with this input

\`\`\`
${testLogUrl || "NO LOG URL PROVIDED"}
\`\`\`

**Testcase context:**
- **Testcase:** ${testcaseName}
- **Stage:** ${failureStage || "Unknown"}
${jiraLine}- **Skip Reason:** ${exceptionSummary || "N/A"}

\`\`\`
${(exception || "N/A").slice(0, 5000)}
\`\`\`

${stepsLog ? `steps.log snippet:\n\`\`\`\n${stepsLog.slice(0, 3000)}\n\`\`\`\n` : ""}
${nutestTestLog ? `nutest_test.log snippet:\n\`\`\`\n${nutestTestLog.slice(0, 3000)}\n\`\`\`\n` : ""}

### Step 3 — Return structured results

After completing the skill's triage workflow, return your findings as JSON:

\`\`\`json
{
  "root_cause": "Why the test was skipped — deployment failure details with evidence",
  "classification": "Deployment Failure | Config Issue | Infra Issue | Valid Skip | Stale Skip",
  "failing_code": {
    "file": "path/to/file",
    "line_range": "start-end",
    "snippet": "relevant deployment or skip code"
  },
  "suggested_fix": "Actionable fix or next step for the deployment issue",
  "confidence": "High | Medium | Low",
  "related_components": ["service1", "service2"],
  "jira_duplicates": ["ENG-XXXXX"],
  "triage_report": "The full triage report as generated by the skill"
}
\`\`\`

Respond ONLY with the JSON block.`;
}
